#include "hal_data.h"
#include "SerialCompatibility.h"
#include "i2c_sensor.h"
#include "computation.h"
#include "spi_max31723.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void delay(int dt);
void delay(int dt) {
    R_BSP_SoftwareDelay(dt, BSP_DELAY_UNITS_MILLISECONDS);
}

void print_float(float n);
void print_float(float n) {
    int p = 1;
    long long aux;
    if (n < 1) {
        Serial.print((uint8_t*)"0.");
        aux = ((int)(n * 10) % 10);
        Serial.print(aux);
        aux = (int)(n * 100) % 10;
        Serial.print(aux);
        return;
    }

    aux = n;
    Serial.print(aux);
    Serial.print((uint8_t*)".");
    aux = ((int)(n * 10) % 10);
    Serial.print(aux);
    aux = (int)(n * 100) % 10;
    Serial.print(aux);
}

/*******************************************************************************************************************//**
 * main() is generated by the RZA3UL Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    R_BSP_PinAccessEnable();

    Serial.begin(115200);

    uint8_t xyz_axis[6]      = {0};
    float x_axis            = 0.0f;
    float y_axis            = 0.0f;
    float z_axis            = 0.0f;

    init_sensor();
    max31723_init();

    while (true) {
        read_sensor_data(xyz_axis);

        x_axis = (float) (xyz_axis[0] | (xyz_axis[1] << 8));   // X-axis value
        y_axis = (float) (xyz_axis[2] | (xyz_axis[3] << 8));   // Y-axis value
        z_axis = (float) (xyz_axis[4] | (xyz_axis[5] << 8));   // Z-axis value

        if ((int)x_axis == 0 && (int)y_axis == 0 && (int)z_axis == 0) {
            i2cok = false;
        }

        float temp = get_temperature();
        if ((int) temp == 0 || (int)temp == 255) {
            spiok = false;
        }

        multiplyMatrix();

       Serial.print((uint8_t*) "Computation status [");
       Serial.print((uint8_t*) "\033[0;42mOK\033[0m");
       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*) ", ");

       Serial.print((uint8_t*) "SPI status [");
       if (spiok) {
           Serial.print((uint8_t*) "\033[0;42mOK\033[0m");
       }
       else {
           Serial.print((uint8_t*) "\033[0;41mNOK\033[0m");
       }
       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*) ", ");

       Serial.print((uint8_t*) "I2C status [");
       if (i2cok) {
           Serial.print((uint8_t*) "\033[0;42mOK\033[0m");
       }
       else {
           Serial.print((uint8_t*) "\033[0;41mNOK\033[0m");
       }

       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*) ", ");

       Serial.print((uint8_t*) "temperature [");
       if (spiok) {
           print_float(temp);
           Serial.print((uint8_t*) "°C");
       }
       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*) ", ");

       Serial.print((uint8_t*) "acceleration(x, y, z) [");
       if (i2cok) {
           print_float(x_axis);
       }
       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*)"[");
       if (i2cok) {
           print_float(y_axis);
       }
       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*)"[");
       if (i2cok) {
           print_float(z_axis);
       }

       Serial.print((uint8_t*)"]");
       Serial.print((uint8_t*) "\r\n");

       delay(1000);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}
