#include "hal_data.h"
#include "SerialCompatibility.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void delay(int t);
void delay(int t) {
    R_BSP_SoftwareDelay(t, BSP_DELAY_UNITS_MILLISECONDS);
}

/*******************************************************************************************************************//**
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    R_BSP_PinAccessEnable();

    Serial.begin(115200);

    /* Array of pins to control */
    const bsp_io_port_pin_t pins[] = {
        BSP_IO_PORT_11_PIN_00, // D5
        BSP_IO_PORT_11_PIN_01, // D6
        BSP_IO_PORT_10_PIN_00, // D9
        BSP_IO_PORT_10_PIN_01, // D10
        BSP_IO_PORT_08_PIN_03, // D11
        BSP_IO_PORT_08_PIN_02, // D12
        BSP_IO_PORT_09_PIN_04, // D13
        BSP_IO_PORT_01_PIN_01  // D14
    };

    const size_t pin_count = sizeof(pins) / sizeof(pins[0]);

    while (true)
    {
        for (size_t i = 0; i < pin_count; ++i)
        {
            /* Set pin LOW */
            R_BSP_PinWrite(pins[i], BSP_IO_LEVEL_LOW);
            //APP_PRINT("Pin %u LOW\n", i);
            Serial.println((uint8_t*)"Pin %u LOW\n");
            Serial.println(i);
            delay(50);

            /* Set pin HIGH */
            R_BSP_PinWrite(pins[i], BSP_IO_LEVEL_HIGH);
            Serial.println((uint8_t*)"Pin %u HIGH\n");
            Serial.println(i);
            //APP_PRINT("Pin %u HIGH\n", i);
            delay(50);
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}
